export interface DummySampleProduct {
  id: string
  name: string
  price: number
  description: string
  category: string
  sku: string
  stock: number
  image: string
}

export const DUMMY_CATEGORIES = [
  'Clothing',
  'Jewellery',
  'Electronics',
  'Beauty',
  'Home Decor',
] as const

export type DummyCategory = typeof DUMMY_CATEGORIES[number]

export const DUMMY_PRODUCTS_BY_CATEGORY: Record<DummyCategory, DummySampleProduct[]> = {
  Clothing: [
    {
      id: 'sp-clo-1',
      name: 'Classic Linen Shirt',
      price: 68,
      description: 'Lightweight breathable linen shirt with relaxed collar.',
      category: 'Clothing',
      sku: 'CLO-SHR-01',
      stock: 25,
      image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'sp-clo-2',
      name: 'Everyday Cotton T-Shirt',
      price: 34,
      description: 'Soft 100% organic cotton tee with classic crew neck.',
      category: 'Clothing',
      sku: 'CLO-TSH-02',
      stock: 40,
      image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'sp-clo-3',
      name: 'Relaxed Fit Trousers',
      price: 88,
      description: 'Tailored casual trousers with elasticated waistband.',
      category: 'Clothing',
      sku: 'CLO-TRS-03',
      stock: 18,
      image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'sp-clo-4',
      name: 'Minimalist Summer Dress',
      price: 95,
      description: 'Flowy sleeveless dress with subtle side pockets.',
      category: 'Clothing',
      sku: 'CLO-DRS-04',
      stock: 12,
      image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'sp-clo-5',
      name: 'Casual Denim Jacket',
      price: 120,
      description: 'Timeless wash cotton denim jacket with metal shank buttons.',
      category: 'Clothing',
      sku: 'CLO-JKT-05',
      stock: 15,
      image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
    },
  ],
  Jewellery: [
    {
      id: 'sp-jwl-1',
      name: 'Gold-Plated Hoop Earrings',
      price: 45,
      description: '18k gold-plated hypoallergenic lightweight hoops.',
      category: 'Jewellery',
      sku: 'JWL-ERP-01',
      stock: 30,
      image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'sp-jwl-2',
      name: 'Minimal Pendant Necklace',
      price: 65,
      description: 'Delicate gold chain featuring a geometric coin pendant.',
      category: 'Jewellery',
      sku: 'JWL-NCK-02',
      stock: 20,
      image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'sp-jwl-3',
      name: 'Pearl Bracelet',
      price: 52,
      description: 'Hand-strung freshwater cultured pearls with lobster clasp.',
      category: 'Jewellery',
      sku: 'JWL-BRC-03',
      stock: 25,
      image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'sp-jwl-4',
      name: 'Silver Stackable Ring',
      price: 38,
      description: '925 sterling silver minimalist band with polished finish.',
      category: 'Jewellery',
      sku: 'JWL-RNG-04',
      stock: 40,
      image: 'https://images.unsplash.com/photo-1605100804763-247f673f224e?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'sp-jwl-5',
      name: 'Statement Earrings',
      price: 58,
      description: 'Artisanal hammered brass drop earrings.',
      category: 'Jewellery',
      sku: 'JWL-ERP-05',
      stock: 15,
      image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=800&q=80',
    },
  ],
  Electronics: [
    {
      id: 'sp-elc-1',
      name: 'Wireless Earbuds',
      price: 129,
      description: 'True wireless stereo earbuds with active noise cancellation.',
      category: 'Electronics',
      sku: 'ELC-EBD-01',
      stock: 35,
      image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'sp-elc-2',
      name: 'Portable Bluetooth Speaker',
      price: 79,
      description: 'Waterproof 360-degree sound speaker with 12-hour playtime.',
      category: 'Electronics',
      sku: 'ELC-SPK-02',
      stock: 22,
      image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'sp-elc-3',
      name: 'Wireless Charging Pad',
      price: 35,
      description: 'Fast 15W Qi-certified slim magnetic charging pad.',
      category: 'Electronics',
      sku: 'ELC-CHG-03',
      stock: 50,
      image: 'https://images.unsplash.com/photo-1622445262464-84b14e073541?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'sp-elc-4',
      name: 'Compact Power Bank',
      price: 42,
      description: '10,000mAh dual USB-C fast charging portable battery.',
      category: 'Electronics',
      sku: 'ELC-PWR-04',
      stock: 40,
      image: 'https://images.unsplash.com/photo-1609592424009-410a560f8546?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'sp-elc-5',
      name: 'Smart Desk Lamp',
      price: 89,
      description: 'Dimmable LED lamp with color temperature controls and timer.',
      category: 'Electronics',
      sku: 'ELC-LMP-05',
      stock: 18,
      image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80',
    },
  ],
  Beauty: [
    {
      id: 'sp-bty-1',
      name: 'Hydrating Face Serum',
      price: 48,
      description: 'Hyaluronic acid and vitamin B5 serum for deep hydration.',
      category: 'Beauty',
      sku: 'BTY-SRM-01',
      stock: 30,
      image: 'https://images.unsplash.com/photo-1608248597359-0a68d0f19c96?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'sp-bty-2',
      name: 'Gentle Facial Cleanser',
      price: 28,
      description: 'pH-balanced foaming cleanser infused with chamomile.',
      category: 'Beauty',
      sku: 'BTY-CLN-02',
      stock: 45,
      image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'sp-bty-3',
      name: 'Nourishing Lip Balm',
      price: 14,
      description: 'Organic shea butter and coconut oil hydrating lip balm.',
      category: 'Beauty',
      sku: 'BTY-LIP-03',
      stock: 60,
      image: 'https://images.unsplash.com/photo-1586024467005-4c07b4f5dc7f?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'sp-bty-4',
      name: 'Daily Moisturizer',
      price: 36,
      description: 'Lightweight ceramide cream that locks in skin moisture.',
      category: 'Beauty',
      sku: 'BTY-MST-04',
      stock: 25,
      image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'sp-bty-5',
      name: 'Mineral Sunscreen',
      price: 32,
      description: 'SPF 50 broad-spectrum zinc oxide non-greasy sunscreen.',
      category: 'Beauty',
      sku: 'BTY-SPF-05',
      stock: 35,
      image: 'https://images.unsplash.com/photo-1556228578-8d89f4175314?auto=format&fit=crop&w=800&q=80',
    },
  ],
  'Home Decor': [
    {
      id: 'sp-hom-1',
      name: 'Ceramic Table Vase',
      price: 42,
      description: 'Handcrafted matte ceramic vase with contemporary curves.',
      category: 'Home Decor',
      sku: 'HOM-VAS-01',
      stock: 20,
      image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'sp-hom-2',
      name: 'Minimalist Wall Clock',
      price: 55,
      description: 'Silent sweep movement wooden wall clock with clean dial.',
      category: 'Home Decor',
      sku: 'HOM-CLK-02',
      stock: 15,
      image: 'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'sp-hom-3',
      name: 'Decorative Cushion Cover',
      price: 28,
      description: 'Textured linen-cotton blend square cushion cover.',
      category: 'Home Decor',
      sku: 'HOM-CSH-03',
      stock: 40,
      image: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'sp-hom-4',
      name: 'Scented Candle',
      price: 24,
      description: 'Soy wax candle with notes of sandalwood and amber.',
      category: 'Home Decor',
      sku: 'HOM-CND-04',
      stock: 50,
      image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'sp-hom-5',
      name: 'Wooden Desk Organizer',
      price: 38,
      description: 'Natural oak tray for stationary, keys, and everyday items.',
      category: 'Home Decor',
      sku: 'HOM-ORG-05',
      stock: 25,
      image: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=800&q=80',
    },
  ],
}
