import { ThemeConfig, ThemePresetId, CustomThemeSettings } from './types'
export type { ThemeConfig, ThemePresetId, CustomThemeSettings }

export const THEME_PRESETS: Record<ThemePresetId, ThemeConfig> = {
  atelier: {
    id: 'atelier',
    name: 'Atelier',
    type: 'Editorial fashion & luxury goods',
    fontHeadline: "'DM Serif Display', Georgia, serif",
    fontBody: "'Manrope', sans-serif",
    bg: '#f7f3ee',
    surface: '#ffffff',
    surfaceSubtle: '#f2eae1',
    border: '#e6ded4',
    ink: '#27221d',
    inkMuted: '#736b63',
    accent: '#a86043',
    accentHover: '#8f4f36',
    accentForeground: '#ffffff',
    announcementBg: '#27221d',
    announcementInk: '#f7f3ee',
    badgeBg: '#f2eae1',
    badgeInk: '#a86043',
    heroImage: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1600&q=85',
    heroBadge: 'AUTUMN / WINTER 2026',
    heroHeadline: 'Tailored with intent.',
    heroHeadlineEm: 'Crafted forever.',
    heroSubtitle: 'Refined silhouettes and timeless natural fibers, assembled in limited numbered editions.',
    heroCta: 'Explore Collection',
    cardRadius: '4px',
    buttonRadius: '3px',
    tagStyle: 'uppercase tracking-widest font-serif italic text-xs',
    headerVariant: 'centered',
    productCardVariant: 'editorial',
    heroLayout: 'split',
    containerWidth: 'max-w-6xl',
    buttonStyle: 'sharp',
    priceStyle: 'serif-italic',
    badgeStyle: 'square',
    footerStyle: 'editorial'
  },
  market: {
    id: 'market',
    name: 'Market',
    type: 'Local provisions & farmstead',
    fontHeadline: "'Manrope', sans-serif",
    fontBody: "'Manrope', sans-serif",
    bg: '#f2f6ee',
    surface: '#ffffff',
    surfaceSubtle: '#e4edd8',
    border: '#d7e2cb',
    ink: '#1c2d22',
    inkMuted: '#586a5e',
    accent: '#5a8b34',
    accentHover: '#497329',
    accentForeground: '#ffffff',
    announcementBg: '#1c2d22',
    announcementInk: '#dcecd0',
    badgeBg: '#e6f0dc',
    badgeInk: '#466e27',
    heroImage: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1600&q=85',
    heroBadge: 'FARM-DIRECT PROVISIONS',
    heroHeadline: 'Good food from',
    heroHeadlineEm: 'caring growers.',
    heroSubtitle: 'Seasonal harvest, small-batch pantry staples, and kitchen provisions direct from family farms.',
    heroCta: 'Shop Fresh Harvest',
    cardRadius: '12px',
    buttonRadius: '8px',
    tagStyle: 'font-semibold tracking-wide text-xs',
    headerVariant: 'full',
    productCardVariant: 'compact',
    heroLayout: 'banner',
    containerWidth: 'max-w-7xl',
    buttonStyle: 'rounded',
    priceStyle: 'classic',
    badgeStyle: 'pill',
    footerStyle: 'grid'
  },
  forma: {
    id: 'forma',
    name: 'Forma',
    type: 'Home, objects & lifestyle',
    fontHeadline: "'DM Serif Display', serif",
    fontBody: "'Manrope', sans-serif",
    bg: '#efefec',
    surface: '#ffffff',
    surfaceSubtle: '#e5e5e0',
    border: '#dadad2',
    ink: '#191b1d',
    inkMuted: '#676c72',
    accent: '#2c333e',
    accentHover: '#1a1f26',
    accentForeground: '#ffffff',
    announcementBg: '#191b1d',
    announcementInk: '#efefec',
    badgeBg: '#e5e5e0',
    badgeInk: '#191b1d',
    heroImage: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1600&q=85',
    heroBadge: 'SCANDINAVIAN FORM 2026',
    heroHeadline: 'Objects with a',
    heroHeadlineEm: 'quiet presence.',
    heroSubtitle: 'Thoughtful homeware and utilitarian lighting designed to elevate daily domestic rituals.',
    heroCta: 'View Curated Living',
    cardRadius: '6px',
    buttonRadius: '4px',
    tagStyle: 'font-medium tracking-normal text-xs',
    headerVariant: 'minimal',
    productCardVariant: 'minimal',
    heroLayout: 'immersive',
    containerWidth: 'max-w-6xl',
    buttonStyle: 'pill',
    priceStyle: 'classic',
    badgeStyle: 'subtle',
    footerStyle: 'clean'
  },
  circuit: {
    id: 'circuit',
    name: 'Circuit',
    type: 'Technology, audio & gear',
    fontHeadline: "'Manrope', sans-serif",
    fontBody: "'Manrope', sans-serif",
    bg: '#0c1219',
    surface: '#131b24',
    surfaceSubtle: '#1a2431',
    border: '#243242',
    ink: '#f1f5f9',
    inkMuted: '#94a3b8',
    accent: '#10b981',
    accentHover: '#059669',
    accentForeground: '#091016',
    announcementBg: '#10b981',
    announcementInk: '#091016',
    badgeBg: 'rgba(16, 185, 129, 0.15)',
    badgeInk: '#34d399',
    heroImage: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1600&q=85',
    heroBadge: 'ENGINEERED PRECISION',
    heroHeadline: 'Hardware engineered for',
    heroHeadlineEm: 'flow state.',
    heroSubtitle: 'Precision tactile interfaces, studio acoustics, and workstation essentials for builders.',
    heroCta: 'Explore Hardware',
    cardRadius: '10px',
    buttonRadius: '6px',
    tagStyle: 'font-mono uppercase tracking-wider text-xs',
    headerVariant: 'bordered',
    productCardVariant: 'glass',
    heroLayout: 'split',
    containerWidth: 'max-w-screen-2xl',
    buttonStyle: 'outline',
    priceStyle: 'mono',
    badgeStyle: 'glow',
    footerStyle: 'dark'
  }
}

export function resolveTheme(presetId: ThemePresetId, custom?: CustomThemeSettings): ThemeConfig {
  const baseTheme = THEME_PRESETS[presetId] || THEME_PRESETS['atelier']
  if (!custom) return baseTheme

  return {
    ...baseTheme,
    fontHeadline: custom.fontHeadline || baseTheme.fontHeadline,
    fontBody: custom.fontBody || baseTheme.fontBody,
    bg: custom.bgColor || baseTheme.bg,
    surface: custom.surfaceColor || baseTheme.surface,
    accent: custom.accentColor || baseTheme.accent,
    ink: custom.primaryColor || baseTheme.ink,
    heroImage: custom.heroImage || baseTheme.heroImage,
    heroHeadline: custom.heroHeadline || baseTheme.heroHeadline,
    heroHeadlineEm: custom.heroHeadlineEm || baseTheme.heroHeadlineEm,
    heroSubtitle: custom.heroSubtitle || baseTheme.heroSubtitle,
    heroCta: custom.heroCta || baseTheme.heroCta
  }
}
